#***************************************************************
#   Copyright 2023 Hewlett Packard Enterprise Development LP.
#***************************************************************

all:
	gcc host.c -o host -L$(XILINX_XRT)/lib -lxilinxopencl -fopenmp
